#!/bin/bash

# Do not override here, use DOCKER_NEO4J_XMS and DOCKER_NEO4J_XMX env variables for that.
: ${DOCKER_NEO4J_XMS:=512} # wrapper_java_initmemory
: ${DOCKER_NEO4J_XMX:=512} # wrapper_java_maxmemory

# Setting Java Heap Size configuration
sed -i 's/#wrapper.java.initmemory=512/wrapper.java.initmemory='$DOCKER_NEO4J_XMS'/g' /var/lib/neo4j/conf/neo4j-wrapper.conf
sed -i 's/#wrapper.java.maxmemory=512/wrapper.java.maxmemory='$DOCKER_NEO4J_XMX'/g' /var/lib/neo4j/conf/neo4j-wrapper.conf
    
# Start Neo4j
/var/lib/neo4j/bin/neo4j console

