#!/bin/bash

# Do not override here, use DOCKER_NEO4J_XMS and DOCKER_NEO4J_XMX env variables for that.
: ${DOCKER_NEO4J_XMS:=512} # wrapper_java_initmemory
: ${DOCKER_NEO4J_XMX:=512} # wrapper_java_maxmemory

# Setting Java Heap Size configuration
sed -i 's/#dbms.memory.heap.initial_size=512/dbms.memory.heap.initial_size='$DOCKER_NEO4J_XMS'/g' /etc/neo4j/neo4j-wrapper.conf
sed -i 's/#dbms.memory.heap.max_size=512/dbms.memory.heap.max_size='$DOCKER_NEO4J_XMX'/g' /etc/neo4j/neo4j-wrapper.conf
    
# Start Neo4j
/etc/init.d/neo4j restart
tail -f /var/log/neo4j/neo4j.log

